# Container: SBOM (generate → ingest → enforce) → SLSA → artifact signing — keyless OIDC.
name: "V2 container-keyless"

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  container-keyless:
    runs-on: ubuntu-latest
    env:
      HARNESS_ACCOUNT_URL: ${{ vars.HARNESS_ACCOUNT_URL }}
      HARNESS_ACCOUNT_ID: ${{ vars.HARNESS_ACCOUNT_ID }}
      HARNESS_ORG_ID: ${{ vars.HARNESS_ORG_ID }}
      HARNESS_PROJECT_ID: ${{ vars.HARNESS_PROJECT_ID }}
      HARNESS_SSCA_SERVICE_ENDPOINT: ${{ vars.HARNESS_SSCA_SERVICE_ENDPOINT }}
      HARNESS_API_KEY: ${{ secrets.HARNESS_API_KEY }}
      OIDC_PROVIDER: non-harness
      FULCIO_URL: ${{ vars.FULCIO_URL }}
      SSCA_PLUGIN_IMAGE: harness/ssca-plugin:test-githubV2
      SLSA_PLUGIN_IMAGE: harness/slsa-plugin:test-githubV2
      SIGNING_PLUGIN_IMAGE: harness/ssca-artifact-signing-plugin:test-githubV2
      SBOM_SOURCE: ${{ vars.DEVSECOPS_TARGET_IMAGE }}
      SLSA_SOURCE: ${{ vars.DEVSECOPS_TARGET_IMAGE }}
      SOURCE_TYPE: docker
      SBOM_LOCAL_PATH: ${{ vars.SBOM_LOCAL_PATH || '/tmp/sbom' }}

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: sbom-generation
        uses: ./v2/sbom-generation
        with:
          PLUGIN_IMAGE: ${{ env.SSCA_PLUGIN_IMAGE }}
          HARNESS_ACCOUNT_URL: ${{ env.HARNESS_ACCOUNT_URL }}
          HARNESS_API_KEY: ${{ env.HARNESS_API_KEY }}
          HARNESS_ACCOUNT_ID: ${{ env.HARNESS_ACCOUNT_ID }}
          HARNESS_ORG_ID: ${{ env.HARNESS_ORG_ID }}
          HARNESS_PROJECT_ID: ${{ env.HARNESS_PROJECT_ID }}
          HARNESS_SSCA_SERVICE_ENDPOINT: ${{ env.HARNESS_SSCA_SERVICE_ENDPOINT }}
          SBOM_SOURCE: ${{ env.SBOM_SOURCE }}
          SOURCE_TYPE: ${{ env.SOURCE_TYPE }}
          SBOM_TOOL: ${{ vars.SBOM_TOOL || 'Syft' }}
          SBOM_FORMAT: ${{ vars.SBOM_FORMAT || 'cyclonedx-json' }}
          PLUGIN_SBOMDESTINATION: ${{ env.SBOM_LOCAL_PATH }}
          ATTEST_SBOM: "false"
          PLUGIN_KEYLESS_TYPE: non-harness
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: sbom-ingestion
        uses: ./v2/sbom-ingestion
        with:
          PLUGIN_IMAGE: ${{ env.SSCA_PLUGIN_IMAGE }}
          HARNESS_ACCOUNT_URL: ${{ env.HARNESS_ACCOUNT_URL }}
          HARNESS_API_KEY: ${{ env.HARNESS_API_KEY }}
          HARNESS_ACCOUNT_ID: ${{ env.HARNESS_ACCOUNT_ID }}
          HARNESS_ORG_ID: ${{ env.HARNESS_ORG_ID }}
          HARNESS_PROJECT_ID: ${{ env.HARNESS_PROJECT_ID }}
          HARNESS_SSCA_SERVICE_ENDPOINT: ${{ env.HARNESS_SSCA_SERVICE_ENDPOINT }}
          SBOM_SOURCE: ${{ env.SBOM_SOURCE }}
          SOURCE_TYPE: ${{ env.SOURCE_TYPE }}
          PLUGIN_SBOMDESTINATION: ${{ env.SBOM_LOCAL_PATH }}
          ATTEST_SBOM: ${{ vars.ATTEST_SBOM || 'true' }}
          PLUGIN_KEYLESS_TYPE: non-harness
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: sbom-policy-enforcement
        uses: ./v2/sbom-policy-enforcement
        with:
          PLUGIN_IMAGE: ${{ env.SSCA_PLUGIN_IMAGE }}
          HARNESS_ACCOUNT_URL: ${{ env.HARNESS_ACCOUNT_URL }}
          HARNESS_API_KEY: ${{ env.HARNESS_API_KEY }}
          HARNESS_ACCOUNT_ID: ${{ env.HARNESS_ACCOUNT_ID }}
          HARNESS_ORG_ID: ${{ env.HARNESS_ORG_ID }}
          HARNESS_PROJECT_ID: ${{ env.HARNESS_PROJECT_ID }}
          HARNESS_SSCA_SERVICE_ENDPOINT: ${{ env.HARNESS_SSCA_SERVICE_ENDPOINT }}
          SBOM_SOURCE: ${{ env.SBOM_SOURCE }}
          SOURCE_TYPE: ${{ env.SOURCE_TYPE }}
          VERIFY_SBOM: ${{ vars.VERIFY_SBOM || 'true' }}
          POLICY_SET_REF: ${{ vars.OPA_POLICY_SET_REF || 'my_opa_policy_set' }}
          PLUGIN_KEYLESS_TYPE: non-harness
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: slsa-attest
        uses: ./v2/slsa-generation
        with:
          PLUGIN_IMAGE: ${{ env.SLSA_PLUGIN_IMAGE }}
          HARNESS_ACCOUNT_URL: ${{ env.HARNESS_ACCOUNT_URL }}
          HARNESS_API_KEY: ${{ env.HARNESS_API_KEY }}
          HARNESS_ACCOUNT_ID: ${{ env.HARNESS_ACCOUNT_ID }}
          HARNESS_ORG_ID: ${{ env.HARNESS_ORG_ID }}
          HARNESS_PROJECT_ID: ${{ env.HARNESS_PROJECT_ID }}
          HARNESS_SSCA_SERVICE_ENDPOINT: ${{ env.HARNESS_SSCA_SERVICE_ENDPOINT }}
          SLSA_SOURCE: ${{ env.SLSA_SOURCE }}
          SOURCE_TYPE: ${{ env.SOURCE_TYPE }}
          ATTEST_SLSA: ${{ vars.ATTEST_SLSA || 'true' }}
          PLUGIN_KEYLESS_TYPE: non-harness
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: slsa-verify
        uses: ./v2/slsa-verification
        with:
          PLUGIN_IMAGE: ${{ env.SLSA_PLUGIN_IMAGE }}
          HARNESS_ACCOUNT_URL: ${{ env.HARNESS_ACCOUNT_URL }}
          HARNESS_API_KEY: ${{ env.HARNESS_API_KEY }}
          HARNESS_ACCOUNT_ID: ${{ env.HARNESS_ACCOUNT_ID }}
          HARNESS_ORG_ID: ${{ env.HARNESS_ORG_ID }}
          HARNESS_PROJECT_ID: ${{ env.HARNESS_PROJECT_ID }}
          HARNESS_SSCA_SERVICE_ENDPOINT: ${{ env.HARNESS_SSCA_SERVICE_ENDPOINT }}
          SLSA_SOURCE: ${{ env.SLSA_SOURCE }}
          SOURCE_TYPE: ${{ env.SOURCE_TYPE }}
          VERIFY_SLSA: ${{ vars.VERIFY_SLSA || 'true' }}
          PLUGIN_KEYLESS_TYPE: non-harness
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: artifact-sign
        uses: ./v2/artifact-signing
        with:
          PLUGIN_IMAGE: ${{ env.SIGNING_PLUGIN_IMAGE }}
          HARNESS_ACCOUNT_URL: ${{ env.HARNESS_ACCOUNT_URL }}
          HARNESS_API_KEY: ${{ env.HARNESS_API_KEY }}
          HARNESS_ACCOUNT_ID: ${{ env.HARNESS_ACCOUNT_ID }}
          HARNESS_ORG_ID: ${{ env.HARNESS_ORG_ID }}
          HARNESS_PROJECT_ID: ${{ env.HARNESS_PROJECT_ID }}
          HARNESS_SSCA_SERVICE_ENDPOINT: ${{ env.HARNESS_SSCA_SERVICE_ENDPOINT }}
          SIGNING_SOURCE: ${{ env.SLSA_SOURCE }}
          SOURCE_TYPE: ${{ env.SOURCE_TYPE }}
          PLUGIN_KEYLESS_TYPE: non-harness
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: artifact-verify
        uses: ./v2/artifact-verification
        with:
          PLUGIN_IMAGE: ${{ env.SIGNING_PLUGIN_IMAGE }}
          HARNESS_ACCOUNT_URL: ${{ env.HARNESS_ACCOUNT_URL }}
          HARNESS_API_KEY: ${{ env.HARNESS_API_KEY }}
          HARNESS_ACCOUNT_ID: ${{ env.HARNESS_ACCOUNT_ID }}
          HARNESS_ORG_ID: ${{ env.HARNESS_ORG_ID }}
          HARNESS_PROJECT_ID: ${{ env.HARNESS_PROJECT_ID }}
          HARNESS_SSCA_SERVICE_ENDPOINT: ${{ env.HARNESS_SSCA_SERVICE_ENDPOINT }}
          SIGNING_SOURCE: ${{ env.SLSA_SOURCE }}
          SOURCE_TYPE: ${{ env.SOURCE_TYPE }}
          PLUGIN_KEYLESS_TYPE: non-harness
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
