name: Combined Workflow for SLSA Provenance, SBOM, and Policy Enforcement

on:
  push:
    branches: [main]

jobs:
  combined-workflow:
    runs-on: ubuntu-latest
    env: # Centralized environment variables
      HARNESS_ACCOUNT_URL: 'https://reetika.pr2.harness.io'
      HARNESS_AUTH_TOKEN: ${{ secrets.HARNESS_API_KEY }}
      HARNESS_ACCOUNT_ID: 'v7uYjYGtR4qIZAqh_Z-4DQ'
      HARNESS_ORG_ID: 'SSCA'
      HARNESS_PROJECT_ID: 'SSCA_Sanity_Automation'

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Clone Additional Repository
      - name: Clone Additional Repository
        run: |
          git clone https://github.com/reetika04/devsecops-demo.git
          cd devsecops-demo
          echo "Cloned devsecops-demo repository."

      # Step 3: Set Up Java Environment
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Adjust the version based on your project requirements
          distribution: 'temurin'

      # Step 4: Build Project with Maven
      - name: Build Project with Maven
        run: |
          cd devsecops-demo
          mvn clean package
          echo "Maven build completed successfully."

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Build and Tag Docker Image
      - name: Build and Tag Docker Image
        run: |
          cd devsecops-demo
          docker build -t reetika1999/devsecops:latest .
          echo "Docker image built and tagged as reetika1999/devsecops:latest."

      # Step 7: Push the Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push reetika1999/devsecops:latest
          echo "Docker image pushed to Docker Hub."

      # Step 8: Log in to Vault
      - name: Log in to Vault
        uses: hashicorp/vault-action@v2
        id: vault_login
        with:
          url: ${{ secrets.VAULT_URL }}
          method: token
          token: ${{ secrets.VAULT_TOKEN }}

      # Step 9: Set Vault Environment Variables
      - name: Set Vault Environment Variables
        run: |
          echo "VAULT_ADDR=${{ secrets.VAULT_URL }}" >> $GITHUB_ENV
          echo "VAULT_TOKEN=${{ steps.vault_login.outputs.token }}" >> $GITHUB_ENV

      # Step 10: Run SLSA Provenance Action
      - name: Run SLSA Provenance Action
        uses: ./slsa-provenance
        with:
          TARGET: 'reetika1999/devsecops:latest'
          ATTEST_SLSA: false
          KMS_KEY: 'cosign'

      # Step 11: Run SBOM Orchestration Action
      - name: Run SBOM Orchestration Action
        uses: ./sbom-orchestration
        with:
          TOOL: 'Syft'
          FORMAT: 'spdx-json'
          TARGET: 'reetika1999/devsecops:latest'
          ATTEST_SBOM: false
          KMS_KEY: 'cosign'

      # Step 12: Run SBOM Policy Enforcement
      - name: Run SBOM Policy Enforcement Action
        uses: ./sbom-policy-enforcement
        with:
          TARGET: 'reetika1999/devsecops:latest'
          ATTEST_SLSA: false
          KMS_KEY: 'cosign'
          POLICY_SET_REF: 'opa_policy_set_for_at'
